name: Compilar y publicar firmware ESP32

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar código del Repo
        uses: actions/checkout@v4

      - name: 2. Instalar Arduino CLI
        uses: arduino/setup-arduino-cli@v2 # Usamos la v2 que es más estable

      - name: 3. Configurar plataforma ESP32
        run: |
          arduino-cli core update-index
          # Agregamos la URL oficial de ESP32 para que el robot sepa dónde buscar
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: 4. Instalar Librerías
        run: |
          arduino-cli lib install "DHT sensor library"
          arduino-cli lib install "Adafruit Unified Sensor"
          arduino-cli lib install "PubSubClient"
          arduino-cli lib install "ESP32Servo"

      - name: 5. Compilar Firmware
        run: |
          # IMPORTANTE: Asegúrate que el archivo se llame exactamente ESP32SERVER.ino
          arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir ./build ./ESP32SERVER.ino

      - name: 6. Preparar archivos y Actualizar versión
        run: |
          cp ./build/*.bin ./firmware.bin
          # Genera una versión basada en la fecha/hora (ej: 202405201530)
          date +'%Y%m%d%H%M' > version.txt

      - name: 7. Subir cambios al repositorio
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add firmware.bin version.txt
          git commit -m "🚀 Auto-update firmware [skip ci]"
          git push
